name: Build image

on:
  workflow_call:
    inputs:
      context:
        description: Directory with Dockerfile
        required: true
        type: string
      image_name:
        description: Name of the Docker image (e.g. python)
        required: true
        type: string
      image_tag:
        description: Tag for the Docker image (e.g. 3.12)
        required: true
        type: string
      push:
        description: Push image to the registry
        required: true
        type: boolean
        default: false

env:
  REPO_NAME: stepik

jobs:
  build_image:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Check if image tag exists in Docker Hub
        id: check_image
        run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" "https://hub.docker.com/v2/repositories/${{ env.REPO_NAME }}/${{ inputs.image_name }}/tags/${{ inputs.image_tag }}/")
          if [ "$response" -eq 200 ]; then
            echo "Error: Image tag ${{ inputs.image_tag }} already exists!"
            exit 1
          fi
          echo "Image tag does not exist, proceeding with build."

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: ${{ inputs.context }}
          push: ${{ inputs.push }}
          tags: ${{ env.REPO_NAME }}/${{ inputs.image_name }}:${{ inputs.image_tag }}
