name: CI
on:
  push:
    branches:
      - 'master'
      - 'release/**'
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: ${{ github.ref_name != github.event.repository.default_branch }}

jobs:
  build_bash_image:
    name: Build epicbox-base image
    runs-on: [self-hosted, small]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build
        uses: ./.github/workflows/actions/build
        with:
          path: epicbox-base/debian/bullseye
          image_name_tag: debian:bullseye
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          add_hash: false
  build_clojure_image:
    name: Build epicbox-clojure image
    runs-on: [self-hosted, small]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build
        uses: ./.github/workflows/actions/build
        with:
          path: epicbox-clojure
          image_name_tag: clojure:1.9.0.397
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
  build_gcc_image:
    name: Build epicbox-gcc image
    runs-on: [self-hosted, small]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build
        uses: ./.github/workflows/actions/build
        with:
          path: epicbox-gcc
          image_name_tag: gcc:10.2.1
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
  build_go_image:
    name: Build epicbox-go image
    runs-on: [self-hosted, small]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build
        uses: ./.github/workflows/actions/build
        with:
          path: epicbox-go
          image_name_tag: go:1.18.2.1
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
  build_haskell_image:
    name: Build epicbox-haskell image
    runs-on: [self-hosted, small]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build
        uses: ./.github/workflows/actions/build
        with:
          path: epicbox-haskell
          image_name_tag: haskell:8.8.4
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
  build_hyperskill_go_image:
    name: Build epicbox-hyperskill/go image
    runs-on: [self-hosted, small]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build
        uses: ./.github/workflows/actions/build
        with:
          path: epicbox-hyperskill/go
          image_name_tag: hyperskill-go:1.18.2
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
  build_hyperskill_gradle_image:
    name: Build epicbox-hyperskill/gradle image
    runs-on: [self-hosted, small]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build
        uses: ./.github/workflows/actions/build
        with:
          path: epicbox-hyperskill/gradle
          image_name_tag: hyperskill-gradle:7.3-jdk11
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
  build_hyperskill_gradle_spring_image:
    name: Build epicbox-hyperskill/gradle-spring image
    runs-on: [self-hosted, small]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build
        uses: ./.github/workflows/actions/build
        with:
          path: epicbox-hyperskill/gradle-spring
          image_name_tag: hyperskill-gradle-spring:7.3-jdk17
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
  build_hyperskill_java_image:
    name: Build epicbox-hyperskill/java image
    runs-on: [self-hosted, small]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build
        uses: ./.github/workflows/actions/build
        with:
          path: epicbox-hyperskill/java
          image_name_tag: hyperskill-java:17
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
  build_hyperskill_node_image:
    name: Build epicbox-hyperskill/node image
    runs-on: [self-hosted, small]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build
        uses: ./.github/workflows/actions/build
        with:
          path: epicbox-hyperskill/node
          image_name_tag: hyperskill-node:18.17.1
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
  build_hyperskill_node_javascript_image:
    name: Build epicbox-hyperskill/node-javascript image
    runs-on: [self-hosted, small]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build
        uses: ./.github/workflows/actions/build
        with:
          path: epicbox-hyperskill/node-javascript
          image_name_tag: hyperskill-node-javascript:18.17.1
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
  build_hyperskill_python_image:
    name: Build epicbox-hyperskill/python image
    runs-on: [self-hosted, small]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build
        uses: ./.github/workflows/actions/build
        with:
          path: epicbox-hyperskill/python
          image_name_tag: hyperskill-python:3.10
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
  build_java7_image:
    name: Build epicbox/java7 image
    runs-on: [self-hosted, small]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build
        uses: ./.github/workflows/actions/build
        with:
          path: epicbox-java/7
          image_name_tag: java:7u181
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
  build_java8_image:
    name: Build epicbox/java8 image
    runs-on: [self-hosted, small]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build
        uses: ./.github/workflows/actions/build
        with:
          path: epicbox-java/8
          image_name_tag: java:8u181
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
  build_java9_image:
    name: Build epicbox/java9 image
    runs-on: [self-hosted, small]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build
        uses: ./.github/workflows/actions/build
        with:
          path: epicbox-java/9
          image_name_tag: java:9.0.1
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
  build_java11_image:
    name: Build epicbox/java11 image
    runs-on: [self-hosted, small]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build
        uses: ./.github/workflows/actions/build
        with:
          path: epicbox-java/11
          image_name_tag: java:11.0.1
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
  build_java17_image:
    name: Build epicbox/java17 image
    runs-on: [self-hosted, small]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build
        uses: ./.github/workflows/actions/build
        with:
          path: epicbox-java/17
          image_name_tag: java:17.0.1
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
