name: CI
on:
  push:
    branches:
      - 'master'
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build_debian_image:
    name: Build epicbox/debian image
    runs-on: [self-hosted, small]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        uses: ./.github/workflows/actions/build
        with:
          path: epicbox-debian
          image_name_tag: debian:bullseye
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          add_hash: false
  build_clojure_image:
    name: Build epicbox-clojure image
    runs-on: [self-hosted, small]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        uses: ./.github/workflows/actions/build
        with:
          path: epicbox-clojure
          image_name_tag: clojure:1.9.0.397
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
  build_gcc_image:
    name: Build epicbox-gcc image
    needs: build_debian_image
    runs-on: [self-hosted, small]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        uses: ./.github/workflows/actions/build
        with:
          path: epicbox-gcc
          image_name_tag: gcc:10.2.1
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
  build_go_image:
    name: Build epicbox-go image
    runs-on: [self-hosted, small]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        uses: ./.github/workflows/actions/build
        with:
          path: epicbox-go
          image_name_tag: go:1.18.2.1
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
  build_haskell_image:
    name: Build epicbox-haskell image
    runs-on: [self-hosted, small]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        uses: ./.github/workflows/actions/build
        with:
          path: epicbox-haskell
          image_name_tag: haskell:8.8.4
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
  build_hyperskill_go_image:
    name: Build epicbox-hyperskill/go image
    runs-on: [self-hosted, small]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        uses: ./.github/workflows/actions/build
        with:
          path: epicbox-hyperskill/go
          image_name_tag: hyperskill-go:1.18.2
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
  build_hyperskill_gcc_image:
    name: Build epicbox-hyperskill/gcc image
    needs: build_debian_image
    runs-on: [ self-hosted, small ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        uses: ./.github/workflows/actions/build
        with:
          path: epicbox-hyperskill/gcc
          image_name_tag: hyperskill-gcc:10.2.1
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
  build_hyperskill_gradle_image:
    name: Build epicbox-hyperskill/gradle image
    runs-on: [self-hosted, small]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        uses: ./.github/workflows/actions/build
        with:
          path: epicbox-hyperskill/gradle
          image_name_tag: hyperskill-gradle:7.3-jdk11
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
  build_hyperskill_gradle_spring_image:
    name: Build epicbox-hyperskill/gradle-spring image
    runs-on: [self-hosted, small]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        uses: ./.github/workflows/actions/build
        with:
          path: epicbox-hyperskill/gradle-spring
          image_name_tag: hyperskill-gradle-spring:7.3-jdk17
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
  build_hyperskill_java_image:
    name: Build epicbox-hyperskill/java image
    runs-on: [self-hosted, small]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        uses: ./.github/workflows/actions/build
        with:
          path: epicbox-hyperskill/java
          image_name_tag: hyperskill-java:17
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
  build_hyperskill_node_image:
    name: Build epicbox-hyperskill/node image
    runs-on: [self-hosted, small]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        uses: ./.github/workflows/actions/build
        with:
          path: epicbox-hyperskill/node
          image_name_tag: hyperskill-node:18.17.1
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
  build_hyperskill_node_javascript_image:
    name: Build epicbox-hyperskill/node-javascript image
    runs-on: [self-hosted, small]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        uses: ./.github/workflows/actions/build
        with:
          path: epicbox-hyperskill/node-javascript
          image_name_tag: hyperskill-node-javascript:18.17.1
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
  build_hyperskill_python_image:
    name: Build epicbox-hyperskill/python image
    runs-on: [self-hosted, small]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        uses: ./.github/workflows/actions/build
        with:
          path: epicbox-hyperskill/python
          image_name_tag: hyperskill-python:3.10
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
  build_java7_image:
    name: Build epicbox/java7 image
    runs-on: [self-hosted, small]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        uses: ./.github/workflows/actions/build
        with:
          path: epicbox-java/7
          image_name_tag: java:7u181
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
  build_java8_image:
    name: Build epicbox/java8 image
    runs-on: [self-hosted, small]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        uses: ./.github/workflows/actions/build
        with:
          path: epicbox-java/8
          image_name_tag: java:8u181
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
  build_java11_image:
    name: Build epicbox/java11 image
    runs-on: [self-hosted, small]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        uses: ./.github/workflows/actions/build
        with:
          path: epicbox-java/11
          image_name_tag: java:11.0.1
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
  build_java17_image:
    name: Build epicbox/java17 image
    runs-on: [self-hosted, small]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        uses: ./.github/workflows/actions/build
        with:
          path: epicbox-java/17
          image_name_tag: java:17.0.1
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
  build_kotlin_image:
    name: Build epicbox/kotlin image
    runs-on: [self-hosted, small]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        uses: ./.github/workflows/actions/build
        with:
          path: epicbox-kotlin
          image_name_tag: kotlin:1.9.10
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
  build_mono_image:
    name: Build epicbox/mono image
    needs: build_debian_image
    runs-on: [self-hosted, small]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        uses: ./.github/workflows/actions/build
        with:
          path: epicbox-mono
          image_name_tag: mono:6.10.0.104
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
  build_node_image:
    name: Build epicbox/node image
    runs-on: [self-hosted, small]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        uses: ./.github/workflows/actions/build
        with:
          path: epicbox-node
          image_name_tag: node:18.17.1
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
  build_php_image:
    name: Build epicbox/php image
    runs-on: [self-hosted, small]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        uses: ./.github/workflows/actions/build
        with:
          path: epicbox-php
          image_name_tag: php:7.2.6
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
  build_pmd_image:
    name: Build epicbox/pmd image
    runs-on: [self-hosted, small]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        uses: ./.github/workflows/actions/build
        with:
          path: epicbox-pmd
          image_name_tag: pmd:6.9.0
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
  build_python_310_image:
    name: Build epicbox/python 3.10 image
    runs-on: [self-hosted, small]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        uses: ./.github/workflows/actions/build
        with:
          path: epicbox-python/310
          image_name_tag: python:3.10.6
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
  build_python_311_image:
    name: Build epicbox/python 3.11 image
    runs-on: [ self-hosted, small ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        uses: ./.github/workflows/actions/build
        with:
          path: epicbox-python/311
          image_name_tag: python:3.11.5
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
  build_ruby_image:
    name: Build epicbox/ruby image
    runs-on: [self-hosted, small]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        uses: ./.github/workflows/actions/build
        with:
          path: epicbox-ruby
          image_name_tag: ruby:2.5.3
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
  build_scala2_image:
    name: Build epicbox/scala2 image
    runs-on: [self-hosted, small]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        uses: ./.github/workflows/actions/build
        with:
          path: epicbox-scala/2
          image_name_tag: scala:2.13.12
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
  build_scala3_image:
    name: Build epicbox/scala3 image
    runs-on: [self-hosted, small]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        uses: ./.github/workflows/actions/build
        with:
          path: epicbox-scala/3
          image_name_tag: scala:3.0.0
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
  build_typescript_image:
    name: Build epicbox/typescript image
    runs-on: [self-hosted, small]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        uses: ./.github/workflows/actions/build
        with:
          path: epicbox-typescript
          image_name_tag: typescript:4.8.4
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

  clean_untagged_images:
    name: Clean untagged images
    needs: 
      - build_clojure_image
      - build_debian_image
      - build_gcc_image
      - build_go_image
      - build_haskell_image
      - build_hyperskill_gcc_image
      - build_hyperskill_go_image
      - build_hyperskill_gradle_image
      - build_hyperskill_gradle_spring_image
      - build_hyperskill_java_image
      - build_hyperskill_node_image
      - build_hyperskill_node_javascript_image
      - build_hyperskill_python_image
      - build_java7_image
      - build_java8_image
      - build_java11_image
      - build_java17_image
      - build_kotlin_image
      - build_mono_image
      - build_node_image
      - build_php_image
      - build_pmd_image
      - build_python_310_image
      - build_python_311_image
      - build_ruby_image
      - build_scala2_image
      - build_scala3_image
      - build_typescript_image
    runs-on: [self-hosted, small]
    steps:
      - uses: hyperskill/azure-purge-untagged@v2.0.0
        with:
          client_id: ${{ secrets.CLIENT_ID }}
          client_secret: ${{ secrets.CLIENT_SECRET }}
          subscription_id: ${{ secrets.SUBSCRIPTION_ID }}
          tenant_id: ${{ secrets.TENANT_ID }}
          repository_filter: epicbox/.*
          registry: hyperskill
