name: CI
on:
  push:
    branches:
      - 'master'
      - 'release/**'
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: ${{ github.ref_name != github.event.repository.default_branch }}

jobs:
  build_bash_image:
    name: Build epicbox-base image
    runs-on: [self-hosted, small]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build
        uses: ./.github/workflows/actions/build
        with:
          path: epicbox-base/debian/bullseye
          image_name_tag: debian:bullseye
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
  build_clojure_image:
    name: Build epicbox-clojure image
    runs-on: [self-hosted, small]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build
        uses: ./.github/workflows/actions/build
        with:
          path: epicbox-clojure
          image_name_tag: clojure:1.9.0.397-${{ hashFiles('epicbox-clojure/Dockerfile') }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
  build_gcc_image:
    name: Build epicbox-gcc image
    runs-on: [self-hosted, small]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build
        uses: ./.github/workflows/actions/build
        with:
          path: epicbox-gcc
          image_name_tag: gcc:10.2.1-${{ hashFiles('epicbox-gcc/Dockerfile') }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
